site_name: Prometheus Database Exporter
site_version: 1.0.1

nav:
  - Home: index.md
  - Getting Started:
    - Standalone Exporter: getting-started/creating-standalone-exporter.md
    - Configure data source: getting-started/configure-data-source.md
  - About: about.md
theme:
  name: readthedocs