storeConfig:
  type: local # enum [Local, Redis] can add more implementations later by implemnting the DataStore interface
  metadata:
    connectionDetails: {}
collectorConfig:
  type: prometheus # enum [Prometheus] can add more implementations later by implemnting the ICollector interface
  metadata: {}
serverConfig:
  port: 8080
  numWorkers: 5
dataSourceConfig:
  - name: mysql-datastore
    type: mysql # enum [MySQL, PostgreSQL] can add more implementations later by implemnting the IDataSource interface
    metadata:
      connectionDetails:
        host: localhost
        port: 3306
        username: root
        password: password
        connectionString: ""
  - name: postgres-datastore
    type: postgresql # enum [MySQL, PostgreSQL] can add more implementations later by implemnting the IDataSource interface
    metadata:
      connectionDetails:
        host: localhost
        port: 5432
        username: postgres
        password: password
        connectionString: "sslmode=disable"
queries:
  - name: taxi_rides
    dataSource: mysql-datastore
    query: "select count(*) AS total_active_rides from rides where status = 'active';"
    labels: {}
    query_refresh_time: 30s
    query_timeout: 5s
    metrics:
      - name: database
        type: LABEL
        help: "Database name"
        static_value: "rides_db"
      - name: total_active_rides # metric will be taxi_rides_total_active_rides in prometheus
        type: GAUGE
        help: "Total number of active rides"
        column: total_active_rides
