storeConfig:
  type: redis # enum [Local, Redis] can add more implementations later by implemnting the DataStore interface
  metadata:
    connectionDetails:
      host: localhost
      port: 6379
      password: TiyNzDdjvY
collectorConfig:
  type: prometheus # enum [Prometheus] can add more implementations later by implemnting the ICollector interface
  metadata: {}
serverConfig:
  port: 8080
  numWorkers: 5
dataSourceConfig:
  - name: postgres-datastore
    type: SQL # enum [MySQL, PostgreSQL] can add more implementations later by implemnting the IDataSource interface
    metadata:
      connectionDetails:
        host: localhost
        port: 5432
        username: postgres
        password: password
        connectionString: "postgresql://postgres:password@localhost:5432/id3_dashboard?sslmode=disable"

queries:
  - name: taxi_rides
    dataSource: postgres-datastore
    query: "select well_id AS well_name from t_well"
    queryRefreshTime: 30
    queryTimeout: 5
    labels:
      - name: database
        staticValue: id3_dashboard
      - name: test
        columnName: test_col
    metrics:
      - name: well_name # metric will be taxi_rides_total_active_rides in prometheus
        type: GAUGE
        help: "Total number of active rides"
        column: total_active_rides
