enableApi: true
enableCollector: true
schedulerConfig:
  storage: "redis" # enum [redis, sqlite, postgres, memory]
  metadata:
    connectionDetails: 
      host: localhost
      port: 6379
storeConfig:
  type: "local" # enum [Local, Redis] can add more implementations later by implemnting the DataStore interface
  metadata:
    connectionDetails: {} 
      
collectorConfig:
  type: prometheus # enum [Prometheus] can add more implementations later by implemnting the ICollector interface
  metadata: {}
serverConfig:
  port: 8080
  numWorkers: 5
dataSourceConfig:
  - name: postgres-datastore
    type: SQL # enum [MySQL, PostgreSQL] can add more implementations later by implemnting the IDataSource interface
    metadata:
      connectionDetails:
        host: localhost
        port: 5432
        username: postgres
        password: postgres
        connectionString: "postgresql://postgres:postgres@localhost:5432/lego?sslmode=disable"

queries:
  - name: lego_parts_category_count
    dataSource: postgres-datastore
    query: "select lpc.\"name\" as category, count(lpc.\"name\" ) as value from lego_parts lp join lego_part_categories lpc on lp.part_cat_id = lpc.id group by lpc.\"name\" "
    queryRefreshTime: 30
    queryTimeout: 5
    labels:
      - name: category
        columnName: category
    metrics:
      - name: total_wells # metric will be taxi_rides_total_active_rides in prometheus
        type: GAUGE
        help: "Total number of each category of lego parts"
        column: value
