
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI Workflow

on:
  workflow_dispatch:

jobs:

  unit-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Starting unit testing
      run: |
        echo "Starting unit test"
    - name: Fix the packages
      run: |
        git submodule update --init --recursive
    - name: Testing linting
      run: go vet ./... 
    - name: Unit test
      run: go test  ./...
    - run: |
        echo "Testing Successful"

  build-docker-image:
    runs-on: ubuntu-latest
    needs: [unit-testing]
    environment: PROD_ENV
    steps:  
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.4.0
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build Image
      run: |
        echo "Building docker image"
        echo ${{ env.DOCKER_USERNAME }} $DOCKER_USERNAME ${{ vars.DOCKER_USERNAME }}
        TAG_NAME="1.0.0"
        git submodule update --init --recursive
        docker build -t hamzausmani021/prometheus-database-exporter:$TAG_NAME .
        echo "Done bulding docker image and push"

  build-executable:
    runs-on: ubuntu-latest
    needs: [unit-testing]
    steps:  
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - run: git submodule update --init --recursive
    - name: Build Collector
      run: |
        echo "Building collector binary package"
        export GOOS=linux
        echo ${{ vars.DOCKER_USERNAME }}
        # go build -o ./bin/collector ./cmd/collector/
        echo "Done bulding executable"    
    - name: Build Api
      run: |
        echo "Building api binary package"
        export GOOS=linux
        go build  -o ./bin/api ./cmd/api/
        echo "Done bulding executable"

  push-executable-to-s3:
    runs-on: ubuntu-latest
    needs: [build-executable]
    steps:
    - name: Pushing executbale to S3
      run: |
        echo "Uploading to S3"
        sleep 4
        echo "Executable deployed to S3"
    
    
  
        
