name: Integration tests
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

  # push:
  #   tags:
  #     - '*.*.*'

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Run integration tests
        env:
          CONFIG_FILE_PATH: "../../config/config.example.yaml"
        run: |
          git submodule update --init --recursive
          go mod tidy
          ls -al
          go test -tags=integration ./test/integration/...
