
name: Integration tests
on:
  workflow_dispatch:
    
  # push:
  #   tags:
  #     - '*.*.*'

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run integration tests
        run: |
          git submodule update --init --recursive
          go mod tidy
          go test test/integration/...
          
