name: Unit Testing
on:
    workflow_dispatch:

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"
            - name: Starting unit testing
              run: |
                  echo "Starting unit test"
            - name: Fix the packages
              run: |
                  git submodule update --init --recursive
            - name: Testing linting
              run: go vet ./...
            - name: Unit test
              run: go test  ./...
            - name: Golangci-lint
              uses: golangci/golangci-lint-action@v6.0.1
            - run: |
                  echo "Testing Successful"
