name: Tag Verification

on:
    workflow_dispatch:
    workflow_call:
        inputs:
            branch:
                required: false
                type: string
            tagName:
                required: true
                type: string
jobs:
    verify-tags:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: match tags
              run: |
                  TAG_NAME=$(cat .ver)
                  GITHUB_TAG=${{ github.event.inputs.tagName }}
                  echo $GITHUB_TAG $TAG_NAME
                  if [ $TAG_NAME -ne GITHUB_TAG ]; then
                    exit 1
                  fi
