name: Tag Verification
# can only be triggered on Tag
on:
    workflow_dispatch:
    workflow_call:
        inputs:
            ref:
                required: true
                type: string

jobs:
    verify-tags:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}
            - name: match tags
              run: |
                  TAG_NAME=$(cat .ver)
                  GITHUB_TAG=${{ inputs.ref }}
                  echo "tag = $GITHUB_TAG;"
                  echo $GITHUB_TAG $TAG_NAME
                  if [ $TAG_NAME -ne GITHUB_TAG ]; then
                    exit 1
                  fi
